name: Lint Commit Messages

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          # Make sure the full history is available for analysis, not just the
          # most recent commit
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.0.2
        with:
          failOnWarnings: true
